name: 'The title of your GitHub Action'
description: 'The description of your GitHub Action'
branding:
  icon: activity
  color: orange
inputs:
  owner:
    description:
      'The owner of the repo. Assign from github.repository_owner. Example, "dotnet".'
    required: true
  name:
    description:
      'The repository name. Example, "samples".'
    required: true
  branch:
    description:
      'The branch name. Assign from github.ref. Example, "refs/heads/main".'
    required: true
  dir:
    description:
      'The root directory to work from. Examples, "path/to/code".'
    required: false
    default: './'
  batchsize:
    description:
      'The batch size. Assign for create batch lot Example, "2".'
    required: false
  apikey:
    description:
      'The api key. Assign for call API.'
    required: true
  bucketkey:
    description:
      'The bucket key. Assign for call API.'
    required: true
  bucketregion:
    description:
      'The bucket region. Assign for call API.'
    required: true
  bucketsecretkey:
    description:
      'The bucket secret key. Assign for call API.'
    required: true
  inputvalue:
    description:
      'The input value. Assign for process all files or last commit files.'
    required: false
  lastsha:
    description:
      'The last commit sha. Assign for process last commit files.'
    required: false
  githubtoken:
    description:
      'The Github Token. Assign for process get commit files.'
    required: false
  repositorybaseurl:
    description:
      'The Github Reso Base URL. Assign for process API files.'
    required: true
 
outputs:
  summary-title:
    description:
      'The title of the code metrics action.'
  summary-details:
    description:
      'A detailed summary of all the projects that were flagged.'
  updated-metrics:
    description:
      'A boolean value, indicating whether or not the action updated metrics.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-o'
  - ${{ inputs.owner }}
  - '-n'
  - ${{ inputs.name }}
  - '-b'
  - ${{ inputs.branch }}
  - '-d'
  - ${{ inputs.dir }}
  - '-s'
  - ${{inputs.batchsize}}
  - '-k'
  - ${{inputs.apikey}}
  - '-t'
  - ${{inputs.bucketkey}}
  - '-r'
  - ${{inputs.bucketregion}}
  - '-a'
  - ${{inputs.bucketsecretkey}}
  - '-v'
  - ${{inputs.inputvalue}}
  - '-l'
  - ${{inputs.lastsha}}
  - '-g'
  - ${{inputs.githubtoken}}
  - '-u'
  - ${{inputs.repositorybaseurl}}
